#ifndef QTDOCKICON_GLOBAL_H
#define QTDOCKICON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDOCKTILE_LIBRARY)
#  define QTDOCKTILE_EXPORT Q_DECL_EXPORT
#else
#  define QTDOCKTILE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDOCKICON_GLOBAL_H
